### ISSUE TITLE
Scraping_Camille

### ISSUE THREAD

**Issue by camlebrun** [projetgouv/scraping#8]
Je vais tenter un truc pour avancé rapidement

**Comment by camlebrun** [comment]
Code avec le bon rating 

 EDA 
-  Rating ( nb, mean)
- Times series 

Puis data cleaning pour le NLP

Pour avoir le bon rating @OrKashM 

```python
rate_elements = review.find_all('span', class_='kvMYJc')

rate = int(rate_elements[0].get('aria-label').split()[0])
```

**Comment by OrKashM** [comment]
j'ai utilisé ce code mais ça ne marche pas chez moi, je vais te passer le mien et on verra ce que tu as @camlebrun

**Comment by camlebrun** [comment]
Chelou le code ici fonctionne
Je suis entrain de scrape toutes la France @OrKashM

**Comment by OrKashM** [comment]
je compare et je te dis quoi @camlebrun

**Comment by camlebrun** [comment]
@OrKashM  J'ai push un fichier RGPD friendly. On à 74% des données dispo
